---
# references
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/install-CloudWatch-Agent-on-first-instance.html
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/verify-CloudWatch-Agent-Package-Signature.html

# Selective include of vars
- name: Include variables for Ubuntu
  include_vars: "{{ item }}"
  with_first_found:
    - "ubuntu.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Ubuntu'
  tags:
    - include-ubuntu-vars

# Installation tasks
- name: Include tasks for installation on Debian/Ubuntu distribution
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'Debian' and (
      ansible_distribution == 'Debian' or
      ansible_distribution == 'Ubuntu'
    )
  tags:
    - include-debian-tags

# Configuration tasks
- name: Configure {{ cwa_package }}
  include_tasks: "configure.yml"
  tags:
    - configure
